<template>
  <div class="flex flex-wrap gap-2">
    <UiLinkButton
      v-if="socialMedia.instagram?.length"
      :to="`https://instagram.com/${socialMedia.instagram}`"
      target="_blank"
      external
    >
      <Icon
        name="simple-icons:instagram"
        class="size-4"
      />
      Instagram
    </UiLinkButton>
    <UiLinkButton
      v-if="socialMedia.letterboxd?.length"
      :to="`https://letterboxd.com/${socialMedia.letterboxd}`"
      target="_blank"
      external
    >
      <Icon
        name="simple-icons:letterboxd"
        class="size-4"
      />
      Letterboxd
    </UiLinkButton>
    <UiLinkButton
      v-if="socialMedia.trakt?.length"
      :to="`https://trakt.tv/users/${socialMedia.trakt}`"
      target="_blank"
      external
    >
      <Icon
        name="simple-icons:trakt"
        class="size-4"
      />
      Trakt
    </UiLinkButton>
    <UiLinkButton
      v-if="socialMedia.gitHub?.length"
      :to="`https://github.com/${socialMedia.gitHub}`"
      target="_blank"
      external
    >
      <Icon
        name="simple-icons:github"
        class="size-4"
      />
      GitHub
    </UiLinkButton>
    <UiLinkButton
      v-if="socialMedia.linkedin?.length"
      :to="`https://www.linkedin.com/in/${socialMedia.linkedin}`"
      target="_blank"
      external
    >
      <Icon
        name="simple-icons:linkedin"
        class="size-4"
      />
      LinkedIn
    </UiLinkButton>
    <UiLinkButton to="/blog">
      <Icon
        name="lucide:notebook-text"
        class="size-4"
      />
      Blog
    </UiLinkButton>
  </div>
</template>

<script lang="ts" setup>
const { socialMedia } = useAppConfig();
</script>
